# Generated by Django 2.0.2 on 2018-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kinoteatr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino_name', models.CharField(help_text=' ', max_length=200)),
                ('kino_address', models.CharField(help_text=' ', max_length=200)),

                ('phone_number', models.IntField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kino_name', 'kino_address'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' ', max_length=200)),
                ('kinotet', models.CharField(help_text=' ', max_length=200)),

            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
